// src/constants/argentinaLocations.ts
// CREAR ESTE ARCHIVO EN EL BACKEND

export interface Province {
  id: string;
  name: string;
  localities: string[];
}

export const ARGENTINA_PROVINCES: Province[] = [
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    localities: [
      'La Plata',
      'Mar del Plata',
      'Bahía Blanca',
      'Tandil',
      'Olavarría',
      'Pergamino',
      'Junín',
      'Necochea',
      'Tres Arroyos',
      'Azul',
      'San Nicolás',
      'Quilmes',
      'Avellaneda',
      'Lanús',
      'San Isidro',
      'Vicente López',
      'Morón',
      'San Martín',
      'Tigre',
      'Pilar',
      'Escobar',
      'San Miguel',
      'Merlo',
      'Moreno',
      'La Matanza',
      'Lomas de Zamora',
      'Almirante Brown',
      'Esteban Echeverría',
      'Florencio Varela',
      'Berazategui',
    ],
  },
  {
    id: 'caba',
    name: 'Ciudad Autónoma de Buenos Aires',
    localities: [
      'Buenos Aires',
      'Palermo',
      'Recoleta',
      'Belgrano',
      'Caballito',
      'Núñez',
      'Villa Crespo',
      'San Telmo',
      'La Boca',
      'Puerto Madero',
    ],
  },
  {
    id: 'cordoba',
    name: 'Córdoba',
    localities: [
      'Córdoba',
      'Villa Carlos Paz',
      'Río Cuarto',
      'Villa María',
      'San Francisco',
      'Alta Gracia',
      'Jesús María',
      'Bell Ville',
      'Cosquín',
      'La Falda',
      'Villa Allende',
      'Río Tercero',
      'Cruz del Eje',
      'Villa Dolores',
      'Arroyito',
      'Laboulaye',
      'Marcos Juárez',
      'Unquillo',
      'La Calera',
      'Oncativo',
    ],
  },
  {
    id: 'santa-fe',
    name: 'Santa Fe',
    localities: [
      'Rosario',
      'Santa Fe',
      'Rafaela',
      'Venado Tuerto',
      'Reconquista',
      'Villa Gobernador Gálvez',
      'Casilda',
      'Esperanza',
      'Villa Constitución',
      'Santo Tomé',
      'Sunchales',
      'Gálvez',
    ],
  },
  {
    id: 'mendoza',
    name: 'Mendoza',
    localities: [
      'Mendoza',
      'Godoy Cruz',
      'Las Heras',
      'Guaymallén',
      'Maipú',
      'Luján de Cuyo',
      'San Rafael',
      'San Martín',
      'Tunuyán',
      'Rivadavia',
    ],
  },
  {
    id: 'tucuman',
    name: 'Tucumán',
    localities: [
      'San Miguel de Tucumán',
      'Yerba Buena',
      'Tafí Viejo',
      'Banda del Río Salí',
      'Concepción',
      'Aguilares',
      'Monteros',
      'Famaillá',
    ],
  },
  {
    id: 'entre-rios',
    name: 'Entre Ríos',
    localities: [
      'Paraná',
      'Concordia',
      'Gualeguaychú',
      'Concepción del Uruguay',
      'Victoria',
      'Gualeguay',
      'Villaguay',
      'Colón',
    ],
  },
  {
    id: 'salta',
    name: 'Salta',
    localities: [
      'Salta',
      'San Ramón de la Nueva Orán',
      'Tartagal',
      'General Güemes',
      'Metán',
      'Cafayate',
      'Rosario de la Frontera',
    ],
  },
  {
    id: 'misiones',
    name: 'Misiones',
    localities: [
      'Posadas',
      'Puerto Iguazú',
      'Eldorado',
      'Oberá',
      'Apóstoles',
      'Leandro N. Alem',
      'Jardín América',
    ],
  },
  {
    id: 'chaco',
    name: 'Chaco',
    localities: [
      'Resistencia',
      'Barranqueras',
      'Fontana',
      'Presidencia Roque Sáenz Peña',
      'Villa Ángela',
      'Charata',
    ],
  },
  {
    id: 'corrientes',
    name: 'Corrientes',
    localities: [
      'Corrientes',
      'Goya',
      'Paso de los Libres',
      'Curuzú Cuatiá',
      'Mercedes',
      'Santo Tomé',
    ],
  },
  {
    id: 'santiago-del-estero',
    name: 'Santiago del Estero',
    localities: [
      'Santiago del Estero',
      'La Banda',
      'Termas de Río Hondo',
      'Frías',
      'Añatuya',
    ],
  },
  {
    id: 'jujuy',
    name: 'Jujuy',
    localities: [
      'San Salvador de Jujuy',
      'Palpalá',
      'San Pedro de Jujuy',
      'Libertador General San Martín',
      'Perico',
    ],
  },
  {
    id: 'rio-negro',
    name: 'Río Negro',
    localities: [
      'Viedma',
      'San Carlos de Bariloche',
      'General Roca',
      'Cipolletti',
      'Villa Regina',
      'El Bolsón',
    ],
  },
  {
    id: 'neuquen',
    name: 'Neuquén',
    localities: [
      'Neuquén',
      'Cutral Có',
      'Centenario',
      'Plottier',
      'Zapala',
      'San Martín de los Andes',
      'Villa La Angostura',
    ],
  },
  {
    id: 'chubut',
    name: 'Chubut',
    localities: [
      'Comodoro Rivadavia',
      'Puerto Madryn',
      'Trelew',
      'Esquel',
      'Rawson',
    ],
  },
  {
    id: 'formosa',
    name: 'Formosa',
    localities: [
      'Formosa',
      'Clorinda',
      'Pirané',
      'El Colorado',
    ],
  },
  {
    id: 'san-luis',
    name: 'San Luis',
    localities: [
      'San Luis',
      'Villa Mercedes',
      'Merlo',
      'La Punta',
    ],
  },
  {
    id: 'san-juan',
    name: 'San Juan',
    localities: [
      'San Juan',
      'Rivadavia',
      'Chimbas',
      'Rawson',
      'Caucete',
    ],
  },
  {
    id: 'catamarca',
    name: 'Catamarca',
    localities: [
      'San Fernando del Valle de Catamarca',
      'Andalgalá',
      'Belén',
      'Tinogasta',
    ],
  },
  {
    id: 'la-rioja',
    name: 'La Rioja',
    localities: [
      'La Rioja',
      'Chilecito',
      'Chamical',
      'Aimogasta',
    ],
  },
  {
    id: 'la-pampa',
    name: 'La Pampa',
    localities: [
      'Santa Rosa',
      'General Pico',
      'General Acha',
      'Eduardo Castex',
    ],
  },
  {
    id: 'santa-cruz',
    name: 'Santa Cruz',
    localities: [
      'Río Gallegos',
      'Caleta Olivia',
      'Pico Truncado',
      'Puerto Deseado',
      'El Calafate',
    ],
  },
  {
    id: 'tierra-del-fuego',
    name: 'Tierra del Fuego',
    localities: [
      'Ushuaia',
      'Río Grande',
      'Tolhuin',
    ],
  },
];